### ISSUE TITLE
[Bug] 'baseURL' ignored while using 'axiod(config)'

### ISSUE THREAD

**Issue by KaKi87** [roonie007/axiod#27]
```js
const axiodOrAxios = typeof axiod !== 'undefined' ? axiod : typeof axios !== 'undefined' ? axios : undefined;

const client = axiodOrAxios.create({ baseURL: 'https://httpstat.us' });
await client.get('/200');
console.log('Success');
await client({ url: '/200' });
console.log('Success');
```
Expected output (`axios`-like) :
```
Success
Success
```
Actual output :
```
Success
error: Uncaught (in promise) TypeError: Invalid URL
  return fetch(url, fetchRequestObject).then(async (x) => {
         ^
    at opUrlParse (deno:ext/url/00_url.js:52:26)
    at new URL (deno:ext/url/00_url.js:331:20)
    at new Request (deno:ext/fetch/23_request.js:307:27)
    at deno:ext/fetch/26_fetch.js:433:29
    at new Promise (<anonymous>)
    at fetch (deno:ext/fetch/26_fetch.js:429:20)
    at Function.request (https://deno.land/x/axiod@0.26.2/mod.ts:252:10)
    at Object.axiod (https://deno.land/x/axiod@0.26.2/mod.ts:23:16)
```
Thanks

**Comment by roonie007** [comment]
@KaKi87 can open a PR ?

**Comment by KaKi87** [comment]
I am requesting this fix but am not qualified to do it myself, sorry.

**Comment by hrishikesh-k** [comment]
I just came across the same problem and created a PR: https://github.com/roonie007/axiod/pull/30 which can potentially fix it. It's not the best or the cleanest solution, but given how it's currently setup, that's the only way I could come up with. Please review and merge it, so I can use it in production! 😄

**Comment by KaKi87** [comment]
Actually, I'm now using `import axios from 'npm:axios'`, which Deno began supporting a few versions ago.

Thanks anyway

**Comment by hrishikesh-k** [comment]
Oh you're right, we could just use axios directly! I totally forgot!
