### ISSUE TITLE
302 redirects fail

### ISSUE THREAD

**Issue by geoffreysmith** [roonie007/axiod#8]
I don't know if this is a bug or I'm using it wrong:

```
import axiod from "https://deno.land/x/axiod/mod.ts";

await axiod.get("https://httpbin.org/redirect/:1")
console.log("Test")
```
Results:
```
➜ deno run --allow-all ./main.ts

error: Uncaught TypeError: stream is locked.
    at new ReadableStreamDefaultReader (deno:op_crates/fetch/11_streams.js:358:15)
    at acquireReadableStreamDefaultReader (deno:op_crates/fetch/11_streams.js:1029:20)
    at ReadableStream.getReader (deno:op_crates/fetch/11_streams.js:553:16)
    at Response.arrayBuffer (deno:op_crates/fetch/26_fetch.js:870:50)
    at Response.text (deno:op_crates/fetch/26_fetch.js:858:29)
    at mod.ts:192:25
    at async main.ts:13:1

```

**Comment by geoffreysmith** [comment]
I added two unit tests, JSON works, HTML fails:

```
Deno.test("Axiod GET request with JSON response", async () => {
  const data = await axiod.get("https://httpbin.org/json");
  assertNotEquals(data.data, "");
});

Deno.test("Axiod GET request with HTML response", async () => {
  const data = await axiod.get("https://httpbin.org/html");
  assertNotEquals(data.data, "");
});
```
Response
```
Axiod GET request with HTML response
TypeError: stream is locked.
    at new ReadableStreamDefaultReader (deno:op_crates/fetch/11_streams.js:358:15)
    at acquireReadableStreamDefaultReader (deno:op_crates/fetch/11_streams.js:1029:20)
    at ReadableStream.getReader (deno:op_crates/fetch/11_streams.js:553:16)
    at Response.arrayBuffer (deno:op_crates/fetch/26_fetch.js:870:50)
    at Response.text (deno:op_crates/fetch/26_fetch.js:858:29)
    at mod.ts:192:25
    at async request-methods.test.ts:33:16
    at async asyncOpSanitizer (deno:cli/rt/40_testing.js:34:7)
    at async Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:240:13)

```

**Comment by geoffreysmith** [comment]
I see this line of code:

`if (_status >= 200 && _status < 300) {`

Maybe this library isn't really what I'm looking for my project, if it swallows it, probably would want the error to bubble up something better than a read lock error? If the control flow for anything outside of 200-300 is considered a throwable error I would want the error to indicate that. Looks like the issue (https://github.com/roonie007/axiod/issues/7) is somewhat related as the error isn't really useful. I received the same error on that, I believe it has something to do with it not returning json.

I'd be happy to help expand the library but don't want to issue a pull request on functionality that is intentional. Personally I'd consider errors anything that breaks the application and not necessarily a valid return with an HTTP code of say 302 or 401. I created a few unit tests before I stopped. I can finish and issue this as a pull request. I would think if we wanted to truly throw on an error code outside of 200-300 we'd want to return the response object somehow.

Thanks for this great project!

```
// Tests conformance to httpbin 0.9.2
// https://httpbin.org/
// -------------------------------------------------------------------
import {
    assertEquals,
    assertNotEquals,
    assertThrowsAsync,
  } from "https://deno.land/std/testing/asserts.ts";
  import axiod from "./mod.ts";

// HTTP Methods
// Testing different HTTP verbs
// -------------------------------------------------------------------
Deno.test("/delete The request's DELETE parameters.", async () => {
    const response = await axiod.delete("https://httpbin.org/delete");
    assertEquals(response.status, 200);
});

Deno.test("/get The request's query parameters.", async () => {
    const response = await axiod.get("https://httpbin.org/get");
    assertEquals(response.status, 200);
});

Deno.test("/patch The request's PATCH parameters.", async () => {
    const response = await axiod.patch("https://httpbin.org/patch");
    assertEquals(response.status, 200);
});

Deno.test("/post The request's POST parameters.", async () => {
    const response = await axiod.post("https://httpbin.org/post");
    assertEquals(response.status, 200);
});

Deno.test("/put The request's PUT parameters.", async () => {
    const response = await axiod.put("https://httpbin.org/put");
    assertEquals(response.status, 200);
});

// Auth
// Auth methods
// -------------------------------------------------------------------
Deno.test("/basic-auth/{user}/{passwd} Prompts the user for authorization using HTTP Basic Auth. (200)", async () => {
    const response = await axiod.get("https://httpbin.org/basic-auth/user/passwd", {
        withCredentials: true,
        auth: {
          username: "user",
          password: "passwd",
        },
      });
    assertEquals(response.status, 200);
});

Deno.test("/bearer Prompts the user for authorization using bearer authentication. (200)", async () => {
    const response = await axiod.get("https://httpbin.org/bearer", {
        headers: {
            "Authorization": "token",
          }
      });
    assertEquals(response.status, 200);
});

Deno.test("/bearer Prompts the user for authorization using bearer authentication. (401)", async () => {
    const response = await axiod.get("https://httpbin.org/bearer", {
        headers: {
            "Authorization": "token",
          }
      });
    assertEquals(response.status, 401);
});
```

**Comment by geoffreysmith** [comment]
Closing this, upon further review this is tied strongly to an open bug in deno on closing body streams.

**Comment by finalspy** [comment]
@geoffreysmith  Could you please add a link to the Deno open bug on closing body streams ?

**Comment by finalspy** [comment]
FYI I opened a PR #9 which afaik will close axiod issue #7. (May be it's not the cleanes t way, but it solved stream issues on my side)

**Comment by geoffreysmith** [comment]
Here's the bug I believe:

https://github.com/denoland/deno/issues/4735

I asked in the Deno Discord and I'm using their recommended method to fix it:

```
    // Deno bugfix to close connection
    await r.arrayBuffer();
    assertEquals(r.status, 200);
```
Unfortunately this causes the test to timeout I believe before it closes, around 9 seconds. It does pass the test.
